### ISSUE TITLE
Feedback Project 2

### ISSUE THREAD

**Issue by aldimahardiansyah** [muhammadrofi12/EcarRental-ProjectPenweb#1]
Terima kasih telah mengerjakan Project 2, @muhammadrofi12 @syayidmuhammadakbar @Rozakurniawan 

### Berikut beberapa  feedback secara umum:

- Web sudah sesuai dengan tema yang telah ditetapkan.
- Tabel pada halaman admin belum responsive ketika dibuka pada handphone.
- Landing page sudah menerapkan konsep RWD.
- Login sudah menggunakan validasi javascript

### Saran:

- Daftar mobil pada koleksi mobil di landing page dapat menggunakan card bootstrap supaya lebih rapi.

> Semoga ilmunya bermanfaat dan bisa dikontribusikan pada hal yang lebih besar. Jangan pernah berhenti mencari dan menggembangkan minatnya, jika lelah koding silahkan istirahat tapi jangan berhenti dan menyerah.

Salam, Aldi Mahardiansyah.

**Comment by muhammadrofi12** [comment]
Baik kang terimakasih atas feedback nya🙏
